//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fstCopy_Proj5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionEntities : DbContext
    {
        public ElectionEntities()
            : base("name=ElectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<DATES> DATES { get; set; }
        public virtual DbSet<Debates> Debates { get; set; }
        public virtual DbSet<GeneralListCandidates> GeneralListCandidates { get; set; }
        public virtual DbSet<GeneralListing> GeneralListing { get; set; }
        public virtual DbSet<LocalList> LocalList { get; set; }
        public virtual DbSet<LocalListCandidates> LocalListCandidates { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Ads> Ads { get; set; }
    }
}
